### ISSUE TITLE
Text To Speech Issue

### ISSUE THREAD

**Issue by Rigwald** [marxjohnson/moodle-block_accessibility#33]
I am having some issues when using the text-to-speech feature inside a moodle lesson.

When using text-to-speech in the AT Bar, I am getting a strange sound whenever it comes to the end of a sentence.  Is says something like  "a sir conflicts" at the end of the sentence, before going to the next sentence.

It is also using a different voice than selected.  I get the proper voice if I select text outside the lesson box.  It is slow and very understandable.  If I select the text inside the lesson box, it is a female sounding voice, very computer like, and improperly pronounces things, like America (EYE-mayr-ih-kah).  It is as if it is using two different text-to-speech functions.

![image](https://f.cloud.github.com/assets/5655794/1306221/00934c1c-31ac-11e3-85f1-42f8c333f71e.png)

**Comment by marxjohnson** [comment]
Closing as this is an issue with ATBar, not with the block.
