### ISSUE TITLE
(It seems that) Translations should be in AMOS, not within plugin files

### ISSUE THREAD

**Issue by germanvaleroelizondo** [marxjohnson/moodle-block_accessibility#35]
Hi,
Please read http://lang.moodle.org/mod/forum/discuss.php?d=2485 .
Please read this Moodle forum too: https://moodle.org/mod/forum/discuss.php?d=244547 
Nowadays, plugins shoud only have the English languages files within the Lang folder, and all translations must be handled in AMOS.
There are several translations for this very useful plugin already hosted in AMOS.

Thanks in advance.

**Comment by hitteshahuja** [comment]
I've recently updated the plugin for 2.9 and this has resulted in an AMOS language string search ( I hope) . Is there anything else that needs to be done regarding the same?
