### ISSUE TITLE
Accessibility block does not affect website

### ISSUE THREAD

**Issue by CamBanfield** [marxjohnson/moodle-block_accessibility#80]
I'm currently seeing a problem where the accessibility block is not affecting the page, the text sizes and colours remain the same. 

I've performed a few tests and the CSS is being loaded, however I'm seeing "Resource interpreted as Stylesheet but transferred with MIME type text/html"

I have tried this with Moodle 2.7.3 and accessibility block version 2014093000

If you want any more information, i'll be happy to provide it.

**Comment by hrvojegolcic** [comment]
Hi guys! Do you this might solve a problem? Issue #82

**Comment by hrvojegolcic** [comment]
Hi guys! The new version of a block is now published to Moodle Plugin Directory. If you will have a chance to try it out and provide some feedback, I'd be very grateful. Otherwise, no worries. Thanks anyway

Cheers!

**Comment by CamBanfield** [comment]
Hi there,

The issue #82 did indeed fix the problem :)

Thanks!

**Comment by hrvojegolcic** [comment]
Happy to hear that. The issue can be closed then. Thanks once again for your feedback and effort
