### ISSUE TITLE
javascript conflict with chat activity

### ISSUE THREAD

**Issue by jheenan** [marxjohnson/moodle-block_accessibility#83]
Moodle 2.6.2
Accessibility block version = 2014093000;
                             release = '2.2.1';

Chat  - standard - version 2013110500

When opening chat session does not finish loading.
error console reads
Timestamp: 12/01/2015 14:53:15 Error: TypeError: Y.one(...) is null
Source File: ..../lib/javascript.php/1417620325/blocks/accessibility/module.js
Line: 1
Nothing from bebug

**Comment by hrvojegolcic** [comment]
Hi! Thank you for your bug report.
It might be useful for me to get this part of the text inside the brackets:
Y.one(...)
Could you provide it for me please?
I believe it could be solved in the code easily

**Comment by hrvojegolcic** [comment]
I also created a chat session but wasn't able to reproduce the error. Could you provide more details please?

**Comment by jheenan** [comment]
I've replicated it on two different sites - same error.
I'm not sure how to open up the brackets as I am only using the firefox error console

**Comment by hrvojegolcic** [comment]
It's also issue with chat session or?
Do you have any possibility to check Chrome console?

**Comment by jheenan** [comment]
With Chrome
Uncaught TypeError: Cannot read property 'setStyle' of null

**Comment by jheenan** [comment]
![2015-01-15 14_43_56-test_ new chat](https://cloud.githubusercontent.com/assets/1236378/5759353/2c511ce6-9cc5-11e4-80b2-eb1d3636f89f.png)

does that help?

**Comment by hrvojegolcic** [comment]
Sure it helps! Let me review it a little bit more. Hear from you tomorrow.

And this occurs for you only within chat session? or?

**Comment by jheenan** [comment]
Only when using the chat session, remove the accessibility block and it works fine. I have tried different themes as well

**Comment by hrvojegolcic** [comment]
One more thing. I've noticed that the accessibility block is not even visible while using chat session? But the script is obviously loading? Is this correct? There is no block displayed at all?

**Comment by jheenan** [comment]
Yes It is on the course where the chat activity is displayed, but when using the chat it pops up in a new window

**Comment by hrvojegolcic** [comment]
This is now fixed. I'll try to publish a new version of a block (2.2.2) during the day. Thanks a lot for your contribution

**Comment by jheenan** [comment]
Thank you for the quick fix :)

**Comment by jheenan** [comment]
Can you commit the changes to a master rather than a dev branch please

**Comment by hrvojegolcic** [comment]
Hi! Why would you want me to do that? There is actually no master branch in this repo at all. The owner of the repo organized it like this and it should be fine development environment. Just wondering, why you seam to have a problem with it? You can fork one for yourself and name it master if you like. I did as well. Also please note that the plugin is now published to official moodle site:
https://moodle.org/plugins/pluginversions.php?plugin=block_accessibility

**Comment by jheenan** [comment]
Ok thanks for your reply
