### ISSUE TITLE
Internet Explorer (9) - Spinning wheel

### ISSUE THREAD

**Issue by mchaney2010** [marxjohnson/moodle-block_accessibility#89]
When a student, on the front page/my home clicks on one of the setting buttons (yellow bground, blue, black or any of the font size changes) the ajax loading wheel comes up, spins, but never goes away. A workaround is to then refresh the browser. The setting that was clicked is then applied. 

The bug, looking at the console log, is in the use of an if statement that checks the o.response.length on the o object. However the o object is never checked to see if it has a response, thus it throws a not defined error. 

The code in question: /blocks/accessibility/module.js

There appears to be 4 locations where this occurs. A temporary fix seems to be to add a check to see if it is not an undefined property. (See below)

//if (o.response.length > 0) {
if (!(o.response === undefined) && o.response.length > 0) {

**Comment by hrvojegolcic** [comment]
Thank you very much for your issue report. I'll fix it as soon I get back
to office in a few days.

**Comment by hrvojegolcic** [comment]
This is now fixed. Thanks for your feedback
