### ISSUE TITLE
Версия для слабовидящих!

### ISSUE THREAD

**Issue by maxp1986** [marxjohnson/moodle-block_accessibility#98]
Здравствуйте! Каким образом нужно настроить блок "accessibility", что он отображался до авторизации пользователя? (тоесть, как только пользователь зашёл на сайт, и не ввёл логин и пароль. Заранее спасибо.

**Comment by marxjohnson** [comment]
I'm afraid I don't know Russian. Google translate tells me your message says this:

> Hello! How did you want to configure the block "accessibility", that it can be displayed to the user's 
> authorization? (Ie as soon as the user went to the site and has not entered your login and password. 
> Thanks in advance.

I'll reply in English and hope you can translate it back:  

This isn't currently possible. There is an open issue for adding this feature, which may be implemented in the future but I am afraid I cannot tell you when. Please see Issue #63 for more information.

I will close this issue as it is a duplicate.
